### PR TITLE
docs: fix param syntax and improve body desc

### PR DESCRIPTION
**Pull request by lbennett-stacki**

### CODE REVIEW

**Review by EntireTwix — CHANGES_REQUESTED** [review]
* log's count isnt able to be dictated by the request, its decided compile time by the whoever is hosting the webserver
* "the `password` value" bit suggests its a variable when really its just whatever is in the "Password" header

**Comment by lbennett-stacki** [comment]
> * log's count isnt able to be dictated by the request, its decided compile time by the whoever is hosting the webserver

Ahh, I see, will update that

> * "the `password` value" bit suggests its a variable when really its just whatever is in the "Password" header

Hrm, but aren’t there body payloads that are for changing a password and setting a new user password as an admin?

We need 1 password to auth either the current password or the admin user and another password to specify what it’s being changed to or initialised as?

**Comment by lbennett-stacki** [comment]
Updated, also applied prettier formatting, so here are the commits with reviewable changes

* explain where log length is configured: https://github.com/EntireTwix/CCash/pull/16/commits/a988dab36121953fb4f4986ec8b7cb79eccd7af6

* explain password change/create user password body structure: https://github.com/EntireTwix/CCash/pull/16/commits/3649eb2c95aec8d2e55d35110bf0e1c85254ef38

**Comment by EntireTwix** [comment]
The body for new password isn't json

**Review by EntireTwix — APPROVED** [review]

**Pull request merged**
